import type { Metadata } from "next";
import { manrope,montserrat } from "../fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${manrope.variable} ${montserrat.variable}`}>
      <body >
        {children}
      </body>
    </html>
  );
}
